CarCareStore/Models/ErrorViewModel.cs
using System;

namespace CarCareStore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarCareStore/Models/ProductTypes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CarCareStore.Models
{
 
    public class ProductTypes
    {
        public int id { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

CarCareStore/Areas/Admin/Controllers/ProductTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarCareStore.Data;
using CarCareStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarCareStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTypesController : Controller
    {
        private readonly Data.ApplicationDbContext _db;


        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.ProductTypes.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.Add(productTypes);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        //####Edit Product Type####
       
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {

                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);

            if (productType == null)
            {
                return NotFound();
            }

            return View(productType);
        }
        [HttpPost]
        public IActionResult Edit(int id,ProductTypes productTypes)
        {
            if (id != productTypes.id)
            {
              return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Update(productTypes);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }
        //################Details
        public IActionResult Details(int? id)
        {
            if (id == null)
            {

                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);

            if (productType == null)
            {
                return NotFound();
            }

            return View(productType);
        }


        //################Delete############


        public IActionResult Delete(int? id)
        {
            if (id == null)
            {

                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);

            if (productType == null)
            {
                return NotFound();
            }

            return View(productType);
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
                 var productTypes = _db.ProductTypes.Find(id);
                _db.ProductTypes.Remove(productTypes);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
 
        }

    }
}

CarCareStore/Areas/Customer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CarCareStore.Models;

namespace CarCareStore.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your request description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarCareStore/Areas/Admin/Views/ProductTypes/Create.cshtml
@model CarCareStore.Models.ProductTypes

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>ProductTypes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form  asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarCareStore/Areas/Admin/Views/ProductTypes/Delete.cshtml
@model CarCareStore.Models.ProductTypes

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Do you want to delete this?</h3>
<div>
    <h4>ProductTypes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarCareStore/Areas/Admin/Views/ProductTypes/Details.cshtml
@model CarCareStore.Models.ProductTypes

@{
    ViewData["Title"] = "Details";
}

<h2>Edit</h2>

<h4>ProductTypes</h4>
<hr />
<div class="row">
    <div class="col-md-4">

        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" disabled />

        </div>

        <div class="form-group">
            <a class="btn btn-primary" asp-area="Admin" asp-controller="ProductTypes" asp-action="Edit" asp-route-id="@Model.id">Edit</a>
        </div>

    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarCareStore/Areas/Admin/Views/ProductTypes/Edit.cshtml
@model CarCareStore.Models.ProductTypes

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>ProductTypes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="id" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Edit" asp-route-id="@Model.id" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Back to List</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarCareStore/Areas/Admin/Views/ProductTypes/Index.cshtml
@model IEnumerable<CarCareStore.Models.ProductTypes>

@{
    ViewData["Title"] = "Index";
}
<br/><br/>

<div class="row">
    <div class="col-6">
<h2>Product Types</h2>
    </div>
    <div class="col-6 text-right">
        <a class="btn btn-info" asp-action="Create">
            <i class="fa fa-plus" aria-hidden="true"></i> <!--Plus Icon-->
            &nbsp; New Product Type
        </a>
    </div>
</div>


<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>

            <th class="text-right">
                <label>Operations</label>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="text-right">
           <partial name="_TableButtonsPartial" model="item.id" />
            </td>
        </tr>
}
    </tbody>
</table>

CarCareStore/Areas/Customer/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

CarCareStore/Areas/Customer/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>